name: Step 6 · Cleanup After Production Deployment

# This workflow updates from step 6 to step 7 (wrap-up or future step)

# It triggers after the "Configure Azure environment" workflow completes
# on the `prod-deploy` branch.
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Configure Azure environment"]
    types: [completed]
    branches: [prod-deploy]

permissions:
  contents: write

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_destroy_completed:
    name: Cleanup Completed · Finalize Progress
    needs: get_current_step
    if: >-
      ${{ !github.event.repository.is_template
          && needs.get_current_step.outputs.current_step == 6 }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout All Branches
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Promote to Step 7
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 6
          to_step: 7

